=== KyleDerZweite/btd6-atlas/profile/schemas/game-data/round.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Raw round model",
  "type": "object",
  "required": [
    "$type",
    "groups"
  ],
  "properties": {
    "$type": {
      "type": "string",
      "minLength": 1,
      "pattern": "(^|\\.)(RoundModel)(,|$)"
    },
    "name": {
      "type": "string"
    },
    "groups": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "round.schema.json#/$defs/bloonGroup"
      }
    },
    "emissions_": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "model.schema.json#/$defs/model"
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "bloonGroup": {
      "type": "object",
      "required": [
        "$type",
        "bloon",
        "count",
        "start",
        "end"
      ],
      "properties": {
        "$type": {
          "type": "string",
          "minLength": 1,
          "pattern": "(^|\\.)(BloonGroupModel)(,|$)"
        },
        "name": {
          "type": "string"
        },
        "bloon": {
          "type": "string",
          "minLength": 1
        },
        "count": {
          "type": "integer",
          "minimum": 0
        },
        "start": {
          "type": "number"
        },
        "end": {
          "type": "number"
        }
      },
      "additionalProperties": true
    }
  }
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueRoundSet/33.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PinkRegrow",
      "start": 0.0,
      "end": 900.0,
      "count": 80,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PurpleRegrowCamo",
      "start": 900.0,
      "end": 1800.0,
      "count": 30,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 1800.0,
      "end": 3000.0,
      "count": 80,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "CeramicFortified",
      "start": 2700.0,
      "end": 3000.0,
      "count": 30,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 360.0,
      "end": 1560.0,
      "count": 4,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bfb",
      "start": 60.0,
      "end": 960.0,
      "count": 3,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bfb",
      "start": 2400.0,
      "end": 3000.0,
      "count": 6,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/AlternateRoundSet/60.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BfbFortified",
      "start": 0.0,
      "end": 60.0,
      "count": 1,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/BattleCatQuestRoundSet/6.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZebraRegrow",
      "start": 0.0,
      "end": 240.0,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Pink",
      "start": 319.8,
      "end": 919.8,
      "count": 25,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Yellow",
      "start": 648.0,
      "end": 1248.0,
      "count": 75,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/AlternateRoundSet/25.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PinkRegrow",
      "start": 0.0,
      "end": 840.0,
      "count": 22,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PurpleRegrow",
      "start": 1028.3999,
      "end": 1268.3999,
      "count": 10,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestObynTrialRoundSet/11.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "CeramicFortified",
      "start": 0.0,
      "end": 60.0,
      "count": 8,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Pink",
      "start": 268.19998,
      "end": 645.05994,
      "count": 40,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 652.2,
      "end": 1252.2,
      "count": 40,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 900.0,
      "end": 1500.0,
      "count": 2,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/FrontierBase1/97.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bad",
      "start": 0.0,
      "end": 3600.0,
      "count": 1,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DynamiteBloon",
      "start": 0.0,
      "end": 3600.0,
      "count": 90,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "GlassBloon",
      "start": 0.0,
      "end": 3600.0,
      "count": 15,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueDenseSet/54.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bad",
      "start": 0.0,
      "end": 480.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zomg",
      "start": 240.0,
      "end": 1440.0,
      "count": 3,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Pink",
      "start": 240.0,
      "end": 480.0,
      "count": 33,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PinkRegrow",
      "start": 480.0,
      "end": 720.0,
      "count": 33,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PinkCamo",
      "start": 720.0,
      "end": 960.0,
      "count": 33,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PinkRegrowCamo",
      "start": 960.0,
      "end": 1200.0,
      "count": 66,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueImmuneSet/5.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "WhiteRegrowCamo",
      "start": 0.0,
      "end": 720.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 210.0,
      "end": 510.0,
      "count": 6,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BlackRegrowCamo",
      "start": 720.0,
      "end": 1440.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "RainbowRegrow",
      "start": 930.0,
      "end": 1230.0,
      "count": 4,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PurpleRegrowCamo",
      "start": 1380.0,
      "end": 2100.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "RainbowCamo",
      "start": 1590.0,
      "end": 1890.0,
      "count": 3,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}
