=== KyleDerZweite/btd6-atlas/profile/schemas/game-data/round.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Raw round model",
  "type": "object",
  "required": [
    "$type",
    "groups"
  ],
  "properties": {
    "$type": {
      "type": "string",
      "minLength": 1,
      "pattern": "(^|\\.)(RoundModel)(,|$)"
    },
    "name": {
      "type": "string"
    },
    "groups": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "round.schema.json#/$defs/bloonGroup"
      }
    },
    "emissions_": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "model.schema.json#/$defs/model"
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "bloonGroup": {
      "type": "object",
      "required": [
        "$type",
        "bloon",
        "count",
        "start",
        "end"
      ],
      "properties": {
        "$type": {
          "type": "string",
          "minLength": 1,
          "pattern": "(^|\\.)(BloonGroupModel)(,|$)"
        },
        "name": {
          "type": "string"
        },
        "bloon": {
          "type": "string",
          "minLength": 1
        },
        "count": {
          "type": "integer",
          "minimum": 0
        },
        "start": {
          "type": "number"
        },
        "end": {
          "type": "number"
        }
      },
      "additionalProperties": true
    }
  }
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/FrontierBase1/173.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "MoabFortified",
      "start": 0.0,
      "end": 1200.0,
      "count": 53,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 1200.0,
      "count": 18,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bfb",
      "start": 0.0,
      "end": 1200.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zomg",
      "start": 400.2,
      "end": 1200.0,
      "count": 4,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/FrontierRushFinal/67.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "AuraBloon",
      "start": 0.0,
      "end": 300.0,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "YellowCamo",
      "start": 0.0,
      "end": 300.0,
      "count": 99,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bfb",
      "start": 0.0,
      "end": 300.0,
      "count": 6,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zomg",
      "start": 0.0,
      "end": 60.0,
      "count": 1,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestObynTrialRoundSet/12.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Yellow",
      "start": 0.0,
      "end": 300.0,
      "count": 150,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Pink",
      "start": 300.0,
      "end": 600.0,
      "count": 150,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Black",
      "start": 600.0,
      "end": 900.0,
      "count": 75,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "White",
      "start": 900.0,
      "end": 1200.0,
      "count": 75,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Purple",
      "start": 1200.0,
      "end": 1500.0,
      "count": 75,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zebra",
      "start": 1500.0,
      "end": 1800.0,
      "count": 75,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/EnduranceRoundSet/54.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 0.0,
      "end": 540.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "LeadFortified",
      "start": 0.0,
      "end": 540.0,
      "count": 6,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 0.0,
      "end": 540.0,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "MoabFortified",
      "start": 270.0,
      "end": 540.0,
      "count": 2,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestEziliTrialRoundSet/111.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZomgFortified",
      "start": 420.0,
      "end": 780.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zomg",
      "start": 0.0,
      "end": 780.0,
      "count": 17,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Zomg",
      "start": 990.0,
      "end": 1110.0,
      "count": 5,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestGeraldoTrialRoundSet/12.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Lead",
      "start": 0.0,
      "end": 307.80002,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Blue",
      "start": 342.0,
      "end": 706.2,
      "count": 15,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Ceramic",
      "start": 856.2,
      "end": 1043.196,
      "count": 5,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueBloonierSet/76.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "MoabFortified",
      "start": 0.0,
      "end": 720.0,
      "count": 18,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Purple",
      "start": 0.0,
      "end": 1800.0,
      "count": 48,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BadFortified",
      "start": 900.0,
      "end": 1500.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Purple",
      "start": 360.0,
      "end": 660.0,
      "count": 24,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Purple",
      "start": 1080.0,
      "end": 1380.0,
      "count": 24,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bad",
      "start": 0.0,
      "end": 1800.0,
      "count": 3,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/EnduranceRoundSet/68.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 0.0,
      "end": 540.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bfb",
      "start": 270.0,
      "end": 540.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Ceramic",
      "start": 0.0,
      "end": 540.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 0.0,
      "end": 60.0,
      "count": 1,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}
