=== KyleDerZweite/btd6-atlas/profile/schemas/game-data/round.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Raw round model",
  "type": "object",
  "required": [
    "$type",
    "groups"
  ],
  "properties": {
    "$type": {
      "type": "string",
      "minLength": 1,
      "pattern": "(^|\\.)(RoundModel)(,|$)"
    },
    "name": {
      "type": "string"
    },
    "groups": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "round.schema.json#/$defs/bloonGroup"
      }
    },
    "emissions_": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "model.schema.json#/$defs/model"
      }
    }
  },
  "additionalProperties": true,
  "$defs": {
    "bloonGroup": {
      "type": "object",
      "required": [
        "$type",
        "bloon",
        "count",
        "start",
        "end"
      ],
      "properties": {
        "$type": {
          "type": "string",
          "minLength": 1,
          "pattern": "(^|\\.)(BloonGroupModel)(,|$)"
        },
        "name": {
          "type": "string"
        },
        "bloon": {
          "type": "string",
          "minLength": 1
        },
        "count": {
          "type": "integer",
          "minimum": 0
        },
        "start": {
          "type": "number"
        },
        "end": {
          "type": "number"
        }
      },
      "additionalProperties": true
    }
  }
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/AlternateRoundSet/119.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZomgFortified",
      "start": 0.0,
      "end": 2700.0,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BfbFortified",
      "start": 90.0,
      "end": 2790.0,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "MoabFortified",
      "start": 360.0,
      "end": 3060.0,
      "count": 24,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueImmuneSet/72.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "MoabFortified",
      "start": 0.0,
      "end": 1800.0,
      "count": 28,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtFortifiedCamo",
      "start": 300.0,
      "end": 1800.0,
      "count": 14,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BfbFortified",
      "start": 600.0,
      "end": 1800.0,
      "count": 7,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZomgFortified",
      "start": 900.0,
      "end": 1800.0,
      "count": 4,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PurpleCamo",
      "start": 0.0,
      "end": 1800.0,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "GreenCamo",
      "start": 300.0,
      "end": 1800.0,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BlackCamo",
      "start": 600.0,
      "end": 1800.0,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BlueCamo",
      "start": 900.0,
      "end": 1800.0,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BadFortified",
      "start": 1200.0,
      "end": 1800.0,
      "count": 2,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bad",
      "start": 0.0,
      "end": 1800.0,
      "count": 1,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/FrontierRush2/21.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DynamiteBloon",
      "start": 60.0,
      "end": 72.0,
      "count": 4,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DynamiteBloon",
      "start": 180.0,
      "end": 300.0,
      "count": 7,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "BlackRegrowCamo",
      "start": 60.0,
      "end": 240.0,
      "count": 9,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "PurpleRegrow",
      "start": 0.0,
      "end": 300.0,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Ceramic",
      "start": 0.0,
      "end": 90.0,
      "count": 3,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestAdoraTrialRoundSet/15.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Red",
      "start": 0.0,
      "end": 1500.0,
      "count": 20,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 1053.0,
      "end": 1233.0,
      "count": 3,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Green",
      "start": 340.8,
      "end": 1240.8,
      "count": 12,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Yellow",
      "start": 532.2,
      "end": 1252.2,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Blue",
      "start": 166.8,
      "end": 1366.8,
      "count": 15,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestSaudaTrialRoundSet/35.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "White",
      "start": 0.0,
      "end": 408.0,
      "count": 25,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 612.00006,
      "end": 714.00006,
      "count": 5,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Pink",
      "start": 867.00006,
      "end": 1173.0001,
      "count": 35,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Black",
      "start": 1173.0001,
      "end": 1479.0001,
      "count": 30,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RoguePurpleSet/73.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "LeadFortifiedCamo",
      "start": 0.0,
      "end": 1800.0,
      "count": 210,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 1500.0,
      "count": 27,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 1200.0,
      "count": 27,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 900.0,
      "count": 27,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 600.0,
      "count": 27,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "DdtCamo",
      "start": 0.0,
      "end": 300.0,
      "count": 27,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZomgFortified",
      "start": 1500.0,
      "end": 1800.0,
      "count": 5,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Bad",
      "start": 0.0,
      "end": 1800.0,
      "count": 1,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/QuestGwendolinTrialRoundSet/4.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Lead",
      "start": 0.0,
      "end": 612.00006,
      "count": 10,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 51.0,
      "end": 663.0,
      "count": 10,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}

=== KyleDerZweite/btd6-atlas/data/56.3-build-24829026/game-data/Rounds/RogueRoundSet/16.json
{
  "$type": "Il2CppAssets.Scripts.Models.Rounds.RoundModel, Assembly-CSharp",
  "groups": [
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Moab",
      "start": 0.0,
      "end": 1800.0,
      "count": 3,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "GreenCamo",
      "start": 60.0,
      "end": 960.0,
      "count": 24,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "ZebraCamo",
      "start": 900.0,
      "end": 1200.0,
      "count": 5,
      "name": ""
    },
    {
      "$type": "Il2CppAssets.Scripts.Models.Rounds.BloonGroupModel, Assembly-CSharp",
      "bloon": "Rainbow",
      "start": 1140.0,
      "end": 1800.0,
      "count": 7,
      "name": ""
    }
  ],
  "emissions_": null,
  "name": ""
}
